version: '3'
services:
  backend:
    image: me/backend
    network_mode: "host"
    build:
      context: backend
    volumes:
      - ./backend/public:/usr/src/app/public

  frontend:
    image: nginx
    network_mode: "host"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/public:/usr/share/nginx/html:ro
    depends_on:
      - backend
    ports:
      - 80:80
    ulimits:
      nofile: 4096

